### ISSUE TITLE
how is this intended to run ?

### ISSUE THREAD

**Issue by matt-hayden** [matt-hayden/faceswap#1]
via @nqzero:

> ./faceswap.py ~/x?.jpg
Traceback (most recent call last):
  File "./faceswap.py", line 8, in <module>
    from . import *		# some constants are moved into __init__.py
ValueError: Attempted relative import in non-package
> python --version
Python 2.7.12

**Comment by matt-hayden** [comment]
It's a standalone Python package that can be installed with pip. It's not slick enough to _automatically do_ that, but please see the README for the manual steps necessary to install it on your system without colliding with your other Python work.

**Comment by nqzero** [comment]
i needed to import find_packages to get it to install
then, when running `faceswap t1.jpg t2.jpg`, i get:

```
Traceback (most recent call last):
  File "/home/lytles/faceswap-env/bin/faceswap", line 11, in <module>
    load_entry_point('faceswap', 'console_scripts', 'faceswap')()
  File "/home/lytles/install/apps/python/hayden/faceswap/cli.py", line 189, in main
    output_directory = kwargs.pop('--output')
KeyError: '--output'
```

it looks to me as though kwargs doesn't get populated (but i'm a total noob when it comes to python)

**Comment by nqzero** [comment]
editing cli.py and deleting all the kwargs stuff and hardcoding the directories allows faceswap to run
